#!/bin/sh

sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config

sudo yum -y install docker

sudo groupadd docker
sudo usermod -a -G docker mkaesz

sudo systemctl start docker
sudo systemctl enable docker

sudo systemctl stop firewalld
sudo systemctl disable firewalld

curl https://install.terraform.io/ptfe/stable -o install
sudo bash install no-docker no-proxy

echo "source /etc/replicated.alias" >> .bashrc

sudo reboot
