#!/bin/sh

sudo sed 's/enforcing/disabled/g' /etc/selinux/config

sudo systemctl stop firewalld
sudo systemctl disable firewalld

curl https://install.terraform.io/ptfe/stable | sudo bash

echo "source /etc/replicated.alias" >> .bashrc

sudo reboot
